# Tên ứng dụng
spring.application.name=CRM_be

# Thong tin ket noi MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/crm_banhang
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Cau hinh Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.stdout.encoding=UTF-8

# Cau hinh cong chay ung dung (tuy chon)
server.port=8081
spring.main.allow-bean-definition-overriding=true